### PR TITLE
Encoders for objective and objective_settings

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-web/pull/336/

TODO:
 - Add tests
 - Add decoders too??

cc @sbesson

### CODE REVIEW

**Comment by will-moore** [comment]
Sigh: run failed with:
```
py39 run-test: commands[7] | sh -c 'easy_install dist/*.egg'
WARNING: test command found but not installed in testenv
  cmd: /usr/bin/sh
  env: /home/runner/work/omero-marshal/omero-marshal/.tox/py39
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
/usr/bin/sh: 1: easy_install: not found
ERROR: InvocationError for command /usr/bin/sh -c 'easy_install dist/*.egg' (exited with code 127)
___________________________________ summary ____________________________________
ERROR:   py39: commands failed
Error: Process completed with exit code 1.
```

**Comment by sbesson** [comment]
My vote goes towards dropping the deprecated `easy_install` workflow (https://setuptools.pypa.io/en/latest/deprecated/easy_install.html)? @joshmoore @chris-allan: are there cases where this needs to be preserved?

**Comment by joshmoore** [comment]
Not as far as I know.

**Comment by chris-allan** [comment]
I can't imagine anyone is depending on an `easy_install` workflow outside of the tox configuration running inside this repository's GitHub Actions based CI. Prior to 0.7.0, which was our first and only Python 3 compatible release nearly two years ago we weren't even publishing eggs to PyPI but rather the sdist so I can see no downside to changing the test runner execution to not depend on`easy_install`.

**Review by chris-allan — COMMENTED** [review]
Few high level things:

1. Probably don't want to be using Glencoe copyright headers for code coming from UoD
2. For me, decoders are a requirement
3. Tests are certainly a requirement
4. You probably need to think about an Instrument encoder/decoder (big job) to have this be useful

**Pull request closed without merging**
