### PR TITLE
0.6.0 release

### PR DESCRIPTION
**Pull request by sbesson**
- Add OMERO 5.5 to the test matrix (should use the rc images)
- Update version and changelog
- Add Travis/PyPI deployment logic to deploy on tags

### CODE REVIEW

**Comment by sbesson** [comment]
@jburel I don't know we fundamentally need this PR for OMERO 5.5.0. Should we get the former out of the door, cut `omero-marshal 0.6.0` and bump in the following OMERO.py release?

**Comment by jburel** [comment]
@sbesson 5.5 is going out today your plan sounds good

**Comment by sbesson** [comment]
@jburel pushed a final commit updating the release date. Objection to merging and cutting the release?

**Comment by jburel** [comment]
Ready to go

**Pull request merged**
